### PR TITLE
Support for temperature sensors

### PR DESCRIPTION
**Pull request by frli4797**
Adding support for temperature sensors from alarm. 

Strangely enough all (if present) temperature sensors are enumerated in the GetOverview call, but no temperatures are present in the response from that call. A call to GetTemperatures has to be made separately to receive the temperatures. A possible improvement could be to make a call to status() to ensure that there actually are temperature sensors present. However I do not have access to an alarm that does not have sensors which means that I really could not explore options for being a bit more defensive in that sense. 

Note: the word "temperature" is misspelled in the response from Sectoralarm.

### CODE REVIEW

**Comment by perbrage** [comment]
Nice work and nice addition. I also see that you did quite some style formatting and also fixed some of the tests when it comes to the JSON parsing. Thank you. 

The misspelled stuff in their API is just horrible. And I have tried to correct it when I see it in this library's output. Did you do that?

**Comment by perbrage** [comment]
I don't have any sensors, so for me I get a returned empty array. So that seems fine.

I looked at the test you added, and I really think that you should filter away the useless parameters and try to correct the spelling.

Or I can do that after merging the pull request.

**Comment by frli4797** [comment]
> Nice work and nice addition. I also see that you did quite some style formatting and also fixed some of the tests when it comes to the JSON parsing. Thank you.
> 
> The misspelled stuff in their API is just horrible. And I have tried to correct it when I see it in this library's output. Did you do that?

Yes, changed the spelling of "Tempratures" to "Temperatures". :)

**Comment by frli4797** [comment]
> I don't have any sensors, so for me I get a returned empty array. So that seems fine.
> 
> I looked at the test you added, and I really think that you should filter away the useless parameters and try to correct the spelling.
> 
> Or I can do that after merging the pull request.

No, worries. I thought about fixing that, but it slipped my mind. Amended the PR with this change. Thanks for the positive feedback. 

BTW. I'm also working with a Homebridge/Homekit plugin for Sector in case you're a Apple guy. So this is the reason to why I'm particularly interested in getting some more functionality into you excellent little project. (However the plugin is very much boilerplate still.)

**Comment by frli4797** [comment]
Sorry, something went sour when I committed the "unnecessary" fields fix. Looks kind of bad with two identical commits, but...

**Comment by perbrage** [comment]
I will have a look tomorrow! Cheers

**Comment by perbrage** [comment]
Nice work! Merged it!

**Comment by perbrage** [comment]
Btw, you don't happen to have a Yale doorman lock or some such? In my node-red version of the project I have a request to add support for that in this general library. But I don't have such a lock and are looking for someone to help me develop it. I got some information on how to communicate with it, but no way to test it.

**Comment by frli4797** [comment]
Sorry. Wish I had ont though.

sön 28 okt. 2018 kl. 07:38 skrev Per Brage <notifications@github.com>:

**Comment by perbrage** [comment]
No worries! And thank you for the contribution you made!

**Pull request merged**
