### PR TITLE
Refactoring names related to annex arming and status.

### PR DESCRIPTION
**Pull request by frli4797**
Just rectifying some names as discussed.

### CODE REVIEW

**Comment by perbrage** [comment]
Merging this in for now, but won't make a release out of it yet. Let's see if we can all the topics in one bang.

**Comment by frli4797** [comment]
I’d really like a unit test for the notifications but struggling a bit with
it. However other than that I think I’m code complete with that PR.

ons 31 okt. 2018 kl. 19:05 skrev Per Brage <notifications@github.com>:

**Comment by perbrage** [comment]
Did you manage to create a PR for this part?

**Comment by frli4797** [comment]
Except the unit test. Maybe I can submit the pr without it for now. In that
case within a couple of days.

tis 13 nov. 2018 kl. 16:29 skrev Per Brage <notifications@github.com>:

**Comment by perbrage** [comment]
Ok, no worries! I'm not in a rush :)

**Pull request merged**
